FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    curl \
    python3 \
    python3-pip \
    python3-serial \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Installing v1.1.1 using the script that just worked for you
RUN curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh -s 1.1.1

RUN arduino-cli config init && \
    arduino-cli config set board_manager.additional_urls https://espressif.github.io/arduino-esp32/package_esp32_index.json && \
    arduino-cli core update-index && \
    arduino-cli core install esp32:esp32@3.1.0

WORKDIR /build
